---
exclude_paths:
  - '.git/**'
  - 'bin/**'
  - 'obj/**'
  - '**/*.dll'
  - '**/*.exe'
  - 'TestResults/**'
  - 'codacy-coverage-reporter.jar'
  - 'Joker.Api.Test/**'  # Exclude all test files
  - '**.ps1'  # Exclude PowerShell scripts

engines:
  sonarcs:
    enabled: true
    exclude_patterns:
      - 'Joker.Api.Test/**'
    exclude_rules:
      - 'S1313'  # IP addresses should not be hardcoded
  
  lizard:
    enabled: false  # Disable complexity checking (we have our own standards)
  
  checkstyle:
    enabled: false
  
  pmd:
    enabled: false
