---
exclude_paths:
  - '.git/**'
  - 'bin/**'
  - 'obj/**'
  - '**/*.dll'
  - '**/*.exe'
  - 'TestResults/**'
  - 'codacy-coverage-reporter.jar'
  - 'Joker.Api.Test/**'  # Exclude all test files
  - '**.ps1'  # Exclude PowerShell scripts

engines:
  sonarcs:
    enabled: true
    exclude_patterns:
      - 'Joker.Api.Test/**'
    exclude_rules:
      - 'S2360'  # Optional parameters should not be used (valid pattern for modern C# APIs)
      - 'S107'   # Methods should not have too many parameters (optional params are fine)
  
  lizard:
    enabled: false  # Disable complexity checking - switch statements inflate scores
  
  checkstyle:
    enabled: false
  
  pmd:
    enabled: false
